version: 2.1

orbs:
  node: circleci/node@2.1.0
  slack: circleci/slack@3.4.2
  aws-s3: circleci/aws-s3@1.0.15

executors:
  build-executor:
    docker:
      - image: circleci/node:lts

commands:
  setup_environment:
    description: "Export pipeline number as env var"
    parameters:
      version_path:
        type: string
        default: .
    steps:
      - run:
          name: "Export pipeline number"
          command: |
            echo "export PIPELINE_NUM=<< pipeline.number >>" >> $BASH_ENV
            echo "export VERSION=$(cat << parameters.version_path >>/package.json | grep '\"version\":' | sed -e 's/  \"version\": \"//' | sed -e 's/\",//')" >> $BASH_ENV

  add_fingerprint:
    parameters:
      fingerprint:
        type: string
    steps:
      - add_ssh_keys:
          fingerprints: << parameters.fingerprint >>

  jobstatus:
    description: "Send customised status messages to Slack"
    steps:
      - slack/status:
          failure_message: ':red_circle: ${CIRCLE_JOB} job of pipeline ${PIPELINE_NUM} for ${CIRCLE_TAG:-$CIRCLE_BRANCH} by ${CIRCLE_USERNAME} has failed'
          success_message: ':bananadance: ${CIRCLE_JOB} job of pipeline ${PIPELINE_NUM} for ${CIRCLE_TAG:-$CIRCLE_BRANCH} by ${CIRCLE_USERNAME} has passed'

  git_config:
    parameters:
      email:
        type: string
      author:
        type: string
    steps:
      - run:
          name: git configuration
          command: |
            git config --global user.email << parameters.email >>
            git config --global user.name << parameters.author >>
            ssh-keyscan github.com >> ~/.ssh/known_hosts
  git_tag:
    description: "Tag the project"
    parameters:
      tag:
        type: string
      when:
        type: string
        default: on_success
    steps:
      - run:
          name: Git tag
          command: |
            git tag -f << parameters.tag >>
          when: << parameters.when >>
  git_push_tags:
    description: "Push tags to remote repository"
    steps:
      - run:
          name: git push tags
          command: git push -f --tags

jobs:
  build_test:
    executor: build-executor
    steps:
      - checkout
      - setup_environment
      - node/install-packages
      - run: npm run coverage
      - run: npm run compile
      - store_test_results:
          path: ./coverage
      - persist_to_workspace:
          root: .
          paths:
            - .npmrc
            - ./dist
            - ./package-lock.json
            - ./package.json
      # - jobstatus

  publish:
    executor: build-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_environment:
          version_path: /tmp/workspace
      - run:
          name: "publish npm"
          command: cd /tmp/workspace && npm publish
      # - jobstatus

  tag:
    executor: build-executor
    steps:
      - checkout
      - add_fingerprint:
          fingerprint: "76:a5:8e:a6:80:e4:dd:8d:04:fe:53:d2:d1:5e:6c:a9"
      - setup_environment
      - git_config:
          email: circleci@what3words.com
          author: $CIRCLE_USERNAME
      - git_tag:
          tag: v$VERSION
      - git_push_tags

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_test
      - publish:
          context: org-global
          requires:
            - build_test
          filters:
            branches:
              only: main
      - tag:
          requires:
            - publish

